goal_reached:
  reward: 17.5

safe_dist:
  punishment: 0.1

collision:
  punishment: 10

goal_approached:
  reward_factor: 0.5
  penalty_factor: 0.7

reverse_drive:
  penalty: 0.0001

abrupt_vel_change:
  "0":
    vel_idx: 0
    factor: 0.025

  "-1":
    vel_idx: -1
    factor: 0.01

  "1":
    vel_idx: 1
    factor: 0.01