goal_reached:
  reward: 17.5

safe_dist:
  punishment: 0.25

collision:
  punishment: 10

goal_approached:
  reward_factor: 0.4
  penalty_factor: 0.6

distance_traveled:
  consumption_factor: 0.0075

distance_global_plan:
  reward_factor: 0.2
  penalty_factor: 0.3

abrupt_direction_change: null

reverse_drive:
  penalty: 0.0001

abrupt_vel_change:
  "0":
    vel_idx: 0
    factor: 1.0

  "-1":
    vel_idx: -1
    factor: 0.5

  "1":
    vel_idx: 1
    factor: 0.5