contestants:
  - name: teb-basic
    local_planner: teb
    inter_planner: bypass

  - name: teb-aggressive
    local_planner: teb
    inter_planner: aggressive

  - name: teb-polite
    local_planner: teb
    inter_planner: polite