/**:
  ros__parameters:
    stages:
    - config:
        RANDOM:
          dynamic:
            max: 5
            min: 3
            models:
            - actor1
          interactive:
            max: 0
            min: 0
            models:
            - shelf
          static:
            max: 10
            min: 5
            models:
            - shelf
        SCENARIO:
          file: 1.json
      episodes: 5
      map: map_empty
      name: map_empty_random_jackal
      robot: jackal
      tm_obstacles: random
      tm_robots: scenario
    - config:
        RANDOM:
          dynamic:
            max: 5
            min: 3
            models:
            - actor1
          interactive:
            max: 0
            min: 0
            models:
            - shelf
          static:
            max: 10
            min: 5
            models:
            - shelf
        SCENARIO:
          file: 1.json
      episodes: 5
      map: map_empty
      name: map_empty_random_agvota
      robot: agvota
      tm_obstacles: random
      tm_robots: scenario
    - config:
        RANDOM:
          dynamic:
            max: 5
            min: 3
            models:
            - actor1
          interactive:
            max: 0
            min: 0
            models:
            - shelf
          static:
            max: 10
            min: 5
            models:
            - shelf
        SCENARIO:
          file: 1.json
      episodes: 5
      map: map_empty
      name: map_empty_random_cob4
      robot: cob4
      tm_obstacles: random
      tm_robots: scenario
    - config:
        RANDOM:
          dynamic:
            max: 5
            min: 3
            models:
            - actor1
          interactive:
            max: 0
            min: 0
            models:
            - shelf
          static:
            max: 10
            min: 5
            models:
            - shelf
        SCENARIO:
          file: 1.json
      episodes: 5
      map: arena_corridor
      name: arena_corridor_random_jackal
      robot: jackal
      tm_obstacles: random
      tm_robots: scenario
    - config:
        RANDOM:
          dynamic:
            max: 5
            min: 3
            models:
            - actor1
          interactive:
            max: 0
            min: 0
            models:
            - shelf
          static:
            max: 10
            min: 5
            models:
            - shelf
        SCENARIO:
          file: 1.json
      episodes: 5
      map: arena_corridor
      name: arena_corridor_random_agvota
      robot: agvota
      tm_obstacles: random
      tm_robots: scenario
    - config:
        RANDOM:
          dynamic:
            max: 5
            min: 3
            models:
            - actor1
          interactive:
            max: 0
            min: 0
            models:
            - shelf
          static:
            max: 10
            min: 5
            models:
            - shelf
        SCENARIO:
          file: 1.json
      episodes: 5
      map: arena_corridor
      name: arena_corridor_random_cob4
      robot: cob4
      tm_obstacles: random
      tm_robots: scenario
    - config:
        RANDOM:
          dynamic:
            max: 5
            min: 3
            models:
            - actor1
          interactive:
            max: 0
            min: 0
            models:
            - shelf
          static:
            max: 10
            min: 5
            models:
            - shelf
        SCENARIO:
          file: 1.json
      episodes: 5
      map: arena_hospital_small
      name: arena_hospital_small_random_jackal
      robot: jackal
      tm_obstacles: random
      tm_robots: scenario
    - config:
        RANDOM:
          dynamic:
            max: 5
            min: 3
            models:
            - actor1
          interactive:
            max: 0
            min: 0
            models:
            - shelf
          static:
            max: 10
            min: 5
            models:
            - shelf
        SCENARIO:
          file: 1.json
      episodes: 5
      map: arena_hospital_small
      name: arena_hospital_small_random_agvota
      robot: agvota
      tm_obstacles: random
      tm_robots: scenario
    - config:
        RANDOM:
          dynamic:
            max: 5
            min: 3
            models:
            - actor1
          interactive:
            max: 0
            min: 0
            models:
            - shelf
          static:
            max: 10
            min: 5
            models:
            - shelf
        SCENARIO:
          file: 1.json
      episodes: 5
      map: arena_hospital_small
      name: arena_hospital_small_random_cob4
      robot: cob4
      tm_obstacles: random
      tm_robots: scenario
