SCENARIO:
  file: default.json

PARAMETRIZED:
  file: default.xml 

STAGED:
  curriculum: "default.yaml"
  index: 0

RANDOM:
  seed: -1
  static:
    min: 0
    max: 0
    models: ["shelf"]
  interactive:
    min: 0
    max: 0
    models: ["shelf"]
  dynamic:
    min: 1
    max: 3
    models: ["actor1"]
