task_generator_node:
  ros__parameters:
    task:
      parametrized:
        file: default.xml
      random:
        dynamic:
          n: [3, 15]
          models:
          - gazebo_actor
        interactive:
          n: [0, 0]
          models:
          - shelf
        static:
          max: [5, 10]
          models:
          - shelf
        seed: -1
      scenario:
        file: emptysn.json
      staged:
        curriculum: default.yaml
        index: 0
      environment:
        file: canteen.yaml
    hunavsim:       
      parameters:
        max_vel: 0.3
        force_factor_desired: 1.0
        force_factor_obstacle: 1.0
        force_factor_social: 5.0
        force_factor_robot: 0.0