# Training Curriculum 
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)

# Training Curriculum 
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)

- #0
  goal_radius: 1.5
  map_generator:
    algorithm: "rosnav"
    algorithm_config:
    # rosnav:
    #   map_type: indoor
    #   indoor:
    #     corridor_radius: 5
    #     iterations: 100
    #   outdoor:
    #     obstacle_num: 5
    #     obstacle_extra_radius: 1
      map_type: indoor # chose between 'indoor' and 'outdoor'

  # indoor parameters
      indoor:
        corridor_radius: 3 # total corridor diameter = 1+2*corridor_radius
        iterations: 50 # number of nodes for the indoor map algorithm
  static: 0
  dynamic: 15
- #1
  goal_radius: 0.75
  map_generator:
    algorithm: "rosnav"
    algorithm_config:
      map_type: indoor # chose between 'indoor' and 'outdoor'

    # indoor parameters
      indoor:
        corridor_radius: 3 # total corridor diameter = 1+2*corridor_radius
        iterations: 50
  static: 0
  dynamic: 20
- #2
  goal_radius: 0.5
  map_generator:
    algorithm: "rosnav"
    algorithm_config:
      map_type: indoor # chose between 'indoor' and 'outdoor'

    # indoor parameters
      indoor:
        corridor_radius: 3 # total corridor diameter = 1+2*corridor_radius
        iterations: 50
  static: 0
  dynamic: 25
- #3
  goal_radius: 0.3
  map_generator:
    algorithm: "rosnav"
    algorithm_config:
      map_type: indoor # chose between 'indoor' and 'outdoor'

    # indoor parameters
      indoor:
        corridor_radius: 3 # total corridor diameter = 1+2*corridor_radius
        iterations: 50

  static: 0
  dynamic: 25
- #4
  map_generator:
    algorithm: "rosnav"
    algorithm_config:
      map_type: indoor # chose between 'indoor' and 'outdoor'

    # indoor parameters
      indoor:
        corridor_radius: 3 # total corridor diameter = 1+2*corridor_radius
        iterations: 50
  static: 0
  dynamic: 30
- #5
  map_generator:
    algorithm: "rosnav"
    algorithm_config:
      map_type: indoor # chose between 'indoor' and 'outdoor'

    # indoor parameters
      indoor:
        corridor_radius: 3 # total corridor diameter = 1+2*corridor_radius
        iterations: 50
  static: 0
  dynamic: 35
- #6
  map_generator:
    algorithm: "rosnav"
    algorithm_config:
      map_type: indoor # chose between 'indoor' and 'outdoor'

    # indoor parameters
      indoor:
        corridor_radius: 3 # total corridor diameter = 1+2*corridor_radius
        iterations: 45
  static: 0
  dynamic: 50